/*

 TESTMAP1.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : D:\Projects\GBA\4_backgrounds\sprites\BackgroundTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

unsigned char WindowMap[] =
{
  0x13, 0x10, 0x17, 0x17, 0x1A,0x00
};

/* End of TESTMAP1.C */
