/*

 MAZEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : D:\Projects\GBA\11_background_collision\sprites\work\mazetiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define MazeMap1Width 20
#define MazeMap1Height 18
#define MazeMap1Bank 0

extern unsigned char MazeMap1[];

/* End of MAZEMAP.H */
