/*

 TESTMAP1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : D:\Projects\GBA\4_backgrounds\sprites\BackgroundTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define TestMap1Width 40
#define TestMap1Height 18
#define TestMap1Bank 0

extern unsigned char TestMap1[];

/* End of TESTMAP1.H */
